workflows:
  android:
    name: Build APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Ensure Gradle wrapper
        script: |
          if [ ! -f "./gradlew" ]; then
            gradle -v || sdk install gradle 8.5
            gradle wrapper --gradle-version 8.5
          fi
      - name: Build Debug APK
        script: |
          ./gradlew :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
