workflows:
  android:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        GRADLE_VERSION: 8.5
      android:
        image: latest
    scripts:
      - name: Build Debug APK
        script: |
          cd app
          gradle build
    artifacts:
      - app/build/outputs/**/*.apk
